package amyc
package codegen

import scala.language.implicitConversions

import analyzer._
import amyc.ast.Identifier
import amyc.ast.SymbolicTreeModule.{Call => AmyCall, Div => AmyDiv, And => AmyAnd, Or => AmyOr, _}
import amyc.utils.{Context, Pipeline}
import wasm._
import Instructions._
import Utils._

// Generates WebAssembly code for an Amy program
object CodeGen extends Pipeline[(Program, SymbolTable), Module]:
  def run(ctx: Context)(v: (Program, SymbolTable)): Module =
    val (program, table) = v

    // Generate code for an Amy module
    def cgModule(moduleDef: ModuleDef): List[Function] =
      val ModuleDef(name, defs, optExpr) = moduleDef
      // Generate code for all functions
      defs.collect { case fd: FunDef if !builtInFunctions(fullName(name, fd.name)) =>
        cgFunction(fd, name, false)
      } ++
      // Generate code for the "main" function, which contains the module expression
      optExpr.toList.map { expr =>
        val mainFd = FunDef(Identifier.fresh("main"), Nil, TypeTree(IntType), expr)
        cgFunction(mainFd, name, true)
      }

    // Generate code for a function in module 'owner'
    def cgFunction(fd: FunDef, owner: Identifier, isMain: Boolean): Function =
      // Note: We create the wasm function name from a combination of
      // module and function name, since we put everything in the same wasm module.
      val name = fullName(owner, fd.name)
      Function(name, fd.params.size, isMain){ lh =>
        val locals = fd.paramNames.zipWithIndex.toMap
        val body = cgExpr(fd.body)(using locals, lh)
        val comment = Comment(fd.toString)
        if isMain then
          body <:> Drop // Main functions do not return a value,
                        // so we need to drop the value generated by their body
        else
          comment <:> body
      }


    // Generate code for an expression expr.
    // Additional arguments are a mapping from identifiers (parameters and variables) to
    // their index in the wasm local variables, and a LocalsHandler which will generate
    // fresh local slots as required.
    def cgExpr(expr: Expr)(using locals: Map[Identifier, Int], lh: LocalsHandler): Code =
      expr match
        case IntLiteral(i) =>
          // Push i to the stack.
          // The comments are optional but can help you debug.
          Comment(expr.toString) <:> Const(i)

        case Match(scrut, cases) =>

          // Checks if a value matches a pattern.
          // Assumes value is on top of stack (and CONSUMES it)
          // Returns the code to check the value, and a map of bindings.
          def matchAndBind(pat: Pattern): (Code, Map[Identifier, Int]) = pat match
            case IdPattern(id) =>
              val idLocal = lh.getFreshLocal()
              (Comment(pat.toString) <:> 
              // Assign val to id.
              SetLocal(idLocal) <:> 
              // Return true (IdPattern always matches).
              Const(1),
              // Let the code generation of the expression which corresponds to this pattern
              // know that the bound id is at local idLocal.
              Map(id -> idLocal))

            case WildcardPattern =>
              // consume and add 1 (match anything)
              (Drop <:> Const(1), Map.empty) // no bindings

            case LiteralPattern(lit) =>
              ( cgExpr(lit) <:> Eq,   // push literal value then check equality
                Map.empty )           

            case CaseClassPattern(constr, subPatterns) =>
              val constructor_sig = table.getConstructor(constr).get
              val scrut_addr = lh.getFreshLocal()

              // save scrut adress to use multiple times
              // Stack:[scrutAddr]
              val saveScrut = SetLocal(scrut_addr)
              // Stack after: []

              // Check the constructor index
              val checkIndex: Code =
                GetLocal(scrut_addr) <:> Load <:>     // load index from offset 0
                Const(constructor_sig.index) <:>           // push expected index
                Eq                                   // compare it 0 or 1

              
              var field_checks: Code = Code(Nil)
              var field_bindings: Map[Identifier, Int] = Map.empty
              var i = 0
              for sub_pattern <- subPatterns do
                val (subCode, sub_bindings) = matchAndBind(sub_pattern)
                // For each field: load it, then run subpattern's check
                // After loading, the field value is on the stack — exactly the precondition for subCode
                field_checks = field_checks <:>
                  // AND with the previous result: if already 0, skip; else evaluate subpattern
                  If_i32 <:>
                    GetLocal(scrut_addr) <:> adtField(i) <:> Load <:>  // load field i
                    subCode <:>                                        // run subpattern check
                  Else <:>
                    Const(0) <:>
                  End
                field_bindings = field_bindings ++ sub_bindings
                i = i + 1

              ( saveScrut <:> checkIndex <:> field_checks,
                field_bindings )
            
            case _ => ???

          

        case UnitLiteral() =>
          Const(0)

        case BooleanLiteral(b) =>
          Const(if (b) 1 else 0)

        // Arithmetic and comparison: handle lhs and rhs 
        case Minus(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Sub

        case Plus(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Add

        case Times(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Mul

        case LessThan(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Lt_s

        case LessEquals(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Le_s 

        case Mod(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Rem
        
        case AmyDiv(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Div

        case Neg(e) => Const(0) <:> cgExpr(e) <:> Sub // 0 - e to get -e

        case Not(e) => cgExpr(e) <:> Eqz

        case Equals(lhs, rhs) => cgExpr(lhs) <:> cgExpr(rhs) <:> Eq

        case AmyAnd(lhs, rhs) =>
            cgExpr(lhs) <:> If_i32 <:> cgExpr(rhs) <:> Else <:> Const(0) <:> End

        case AmyOr(lhs, rhs) =>
          cgExpr(lhs) <:> If_i32 <:> Const(1) <:> Else <:> cgExpr(rhs) <:> End
        
        case Variable(name) => // get the variable value from the corresponding local
          GetLocal(locals(name))

        case Ite(cond, thenn, elze) =>
          cgExpr(cond) <:> If_i32 <:> cgExpr(thenn) <:> Else <:> cgExpr(elze) <:> End


        case Sequence(expr1, expr2) =>
          cgExpr(expr1) <:> Drop <:> cgExpr(expr2)

        case Let(df, value, body) =>
          val local_index = lh.getFreshLocal()
          cgExpr(value) <:>
          SetLocal(local_index) <:>
          cgExpr(body)(using locals + (df.name -> local_index))
          
        case StringLiteral(s) => // already given 
            mkString(s)

        case Concat(lhs, rhs) =>
            cgExpr(lhs) <:>
            cgExpr(rhs) <:>
            Call("String_concat")

        case Error(msg) =>
          mkString("Error: ") <:>
          cgExpr(msg) <:>
          Call("String_concat") <:>
          Call("Std_printString") <:>
          Unreachable


    case AmyCall(qname, args) =>
       table.getFunction(qname) match
    case Some(function_signature) =>
      // Function call: push args in order, then call by name
      // compile each argument into wasm code.
      var argsCode: Code = Code(Nil)  // start with empty code
      for arg <- args do
        argsCode = argsCode <:> cgExpr(arg)
      
      argsCode <:> Call(fullName(function_signature.owner, qname))

    case None =>
      // not a function, so it must be a constructor.
      table.getConstructor(qname) match
        case Some(constructor_signature) =>
          // allocate the ADT on the heap.
          val abstractDataType_base = lh.getFreshLocal()
          val mem_size = (1 + args.size) * 4

          // Write each field: address = base + 4*(i+1), value = cgExpr(arg)
          var writeFields: Code = Code(Nil)
          var i = 0
          for arg <- args do
            val oneField: Code =
              GetLocal(abstractDataType_base) <:>
              adtField(i) <:>
              cgExpr(arg) <:>
              Store
            writeFields = writeFields <:> oneField
            i = i + 1

          // Save old boundary, which is the base address of the new ADT
          GetGlobal(memoryBoundary) <:> SetLocal(abstractDataType_base) <:>
          // so nested allocs don't overlap
          GetGlobal(memoryBoundary) <:> Const(mem_size) <:> Add <:> SetGlobal(memoryBoundary) <:>
          // write the constructor index at offset 0 from base.
          GetLocal(abstractDataType_base) <:> Const(constructor_signature.index) <:> Store <:>
          writeFields <:>
          // Return the base address
          GetLocal(abstractDataType_base)

        case None =>
          // Unreachable: name analysis guarantees this is a function or constructor.
          Unreachable


               
    case _ => ??? 

    Module(
      program.modules.last.name.name,
      defaultImports,
      globalsNo,
      wasmFunctions ++ (program.modules flatMap cgModule)
    )
end CodeGen
